# Generated by Django 2.0.7 on 2018-07-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_email', models.EmailField(max_length=254)),
                ('device', models.CharField(choices=[('SP', 'Smart Phones'), ('TA', 'Tablet'), ('LC', 'Laptop Computers')], max_length=2, verbose_name='Device')),
                ('url', models.URLField()),
                ('error_found', models.CharField(max_length=5, verbose_name='Error you found')),
                ('steps_to_reproduce', models.TextField(verbose_name='How to reproduce the error?')),
            ],
            options={
                'verbose_name': 'Complains',
            },
        ),
    ]
