# Generated by Django 2.0.7 on 2018-07-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complain',
            options={'verbose_name': 'Complain', 'verbose_name_plural': 'Complains'},
        ),
        migrations.AlterField(
            model_name='complain',
            name='device',
            field=models.CharField(choices=[('SP', 'Smart Phones'), ('TA', 'Tablet'), ('LC', 'Laptop Computers'), ('NO', 'I do not know')], max_length=2, verbose_name='Device'),
        ),
        migrations.AlterField(
            model_name='complain',
            name='error_found',
            field=models.CharField(max_length=60, verbose_name='Error you found(Be Brief)'),
        ),
    ]
