# Generated by Django 2.0.7 on 2018-07-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_auto_20180712_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='screenshot',
            field=models.ImageField(default=1, upload_to='issues_screenshot'),
            preserve_default=False,
        ),
    ]
