# Generated by Django 2.0.7 on 2018-07-19 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_complain_screenshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complain',
            name='screenshot',
        ),
    ]
