# Generated by Django 2.0.7 on 2018-07-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticalParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name of Party')),
                ('founded_on', models.DateField(verbose_name='Date of Establishment')),
                ('ideology', models.TextField()),
                ('seats_in_pradessabha', models.IntegerField()),
                ('seats_in_pratinidhisabha', models.IntegerField()),
                ('chief_of_party', models.CharField(max_length=50, verbose_name='President of Party')),
                ('about', models.TextField()),
                ('headquarter', models.CharField(max_length=50, verbose_name='Headquarter Location')),
            ],
            options={
                'verbose_name': 'Political Party',
                'verbose_name_plural': 'Political Parties',
            },
        ),
    ]
