# Generated by Django 2.0.7 on 2018-07-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('political_parties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicalparty',
            name='party_logo',
            field=models.ImageField(default=1, upload_to='party_logo'),
            preserve_default=False,
        ),
    ]
