# Generated by Django 2.0.7 on 2018-07-21 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('political_divisions', '0001_initial'),
        ('political_parties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sabha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('area', models.IntegerField()),
                ('population', models.IntegerField()),
                ('voters', models.IntegerField()),
                ('is_marginal', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PradeshSabha',
            fields=[
                ('sabha_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='electoral_constituencies.Sabha')),
                ('winner', models.CharField(max_length=50, verbose_name='Member of Provincial Assembly')),
                ('won_political_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pradeshsabha_won_political_party_set', to='political_parties.PoliticalParty')),
            ],
            options={
                'verbose_name': 'Pradesh Sabha',
                'verbose_name_plural': 'Pradesh Sabhas',
            },
            bases=('electoral_constituencies.sabha',),
        ),
        migrations.CreateModel(
            name='PratinidhiSabha',
            fields=[
                ('sabha_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='electoral_constituencies.Sabha')),
                ('winner', models.CharField(max_length=50, verbose_name='Member of House of Representative')),
                ('pradeshsabha_ka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pratinidhisabha_pradeshsabha_ka', to='electoral_constituencies.PradeshSabha')),
                ('pradeshsabha_kha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pratinidhisabha_pradeshsabha_kha', to='electoral_constituencies.PradeshSabha')),
                ('won_political_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pratinidhisabha_won_political_party_set', to='political_parties.PoliticalParty')),
            ],
            options={
                'verbose_name': 'Pratinidhi Sabha',
                'verbose_name_plural': 'Pratinidhi Sabhas',
            },
            bases=('electoral_constituencies.sabha',),
        ),
        migrations.AddField(
            model_name='sabha',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SabhaDistrictSet', to='political_divisions.District'),
        ),
        migrations.AddField(
            model_name='sabha',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sabha_province_set', to='political_divisions.Province'),
        ),
    ]
