# Generated by Django 2.0.7 on 2018-07-21 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_superadmin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_volunteer',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='academic_background',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='is_superadmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='is_volunteer',
            field=models.BooleanField(default=True),
        ),
    ]
