# Generated by Django 2.0.7 on 2018-07-04 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('political_parties', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nominee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='Full Name')),
                ('object_id', models.PositiveIntegerField()),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('academic_background', models.TextField()),
                ('awards', models.TextField()),
                ('net_worth', models.IntegerField()),
                ('ideology', models.TextField()),
                ('is_incumbent', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('political_affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominee_political_affiliation_set', to='political_parties.PoliticalParty')),
            ],
        ),
    ]
