# Generated by Django 2.0.7 on 2018-07-21 08:47

from django.db import migrations, models
import django.db.models.deletion
import gfklookupwidget.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('results', '0001_initial'),
        ('political_parties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nominee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='Full Name')),
                ('image', models.ImageField(upload_to='candidate_image')),
                ('object_id', gfklookupwidget.fields.GfkLookupField()),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('academic_background', models.TextField()),
                ('awards', models.TextField()),
                ('net_worth', models.IntegerField()),
                ('ideology', models.TextField()),
                ('is_incumbent', models.BooleanField(default=False)),
                ('biography', models.TextField(blank=True, null=True)),
                ('Sabha', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'electoral_constituencies'), ('model', 'pradeshsabha')), models.Q(('app_label', 'electoral_constituencies'), ('model', 'pratinidhisabha')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('political_affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominee_political_affiliation_set', to='political_parties.PoliticalParty')),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NomineeResultSet', to='results.Result')),
            ],
        ),
    ]
