# Generated by Django 2.0.7 on 2018-07-04 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nominee',
            old_name='content_type',
            new_name='candidacy_to',
        ),
    ]
