# Generated by Django 2.0.7 on 2018-07-21 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominee',
            name='Sabha',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'electoral_constituencies'), ('model', 'pradeshsabha')), models.Q(('app_label', 'electoral_constituencies'), ('model', 'pratinidhisabha')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='NomineeSabhaSet', to='contenttypes.ContentType'),
        ),
    ]
