# Generated by Django 2.0.7 on 2018-07-04 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_auto_20180704_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominee',
            name='candidacy_to',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'electoral_constituencies'), ('model', 'PradeshSabha')), models.Q(('app_label', 'electoral_constituencies'), ('model', 'PratinidhiSabha')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
