# Generated by Django 2.0.7 on 2018-07-04 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_auto_20180704_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominee',
            name='candidacy_to',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'electoral_constituencies'), ('model', 'pradeshsabha')), models.Q(('app_label', 'electoral_constituencies'), ('model', 'pratinidhisabha')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
