# Generated by Django 2.0.7 on 2018-07-04 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_auto_20180704_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nominee',
            old_name='candidacy_to',
            new_name='content_type',
        ),
    ]
