# Generated by Django 2.0.7 on 2018-07-06 18:06

from django.db import migrations
import gfklookupwidget.fields


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_auto_20180704_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominee',
            name='object_id',
            field=gfklookupwidget.fields.GfkLookupField(),
        ),
    ]
