# Generated by Django 2.0.7 on 2018-07-19 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0008_nominee_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominee',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NomineeResultSet', to='results.Result'),
        ),
    ]
