# Generated by Django 2.0.7 on 2018-07-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0009_auto_20180719_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominee',
            name='image',
            field=models.ImageField(default=1, upload_to='candidate_image'),
            preserve_default=False,
        ),
    ]
