# Generated by Django 2.0.7 on 2018-07-19 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0009_auto_20180719_1450'),
        ('candidates', '0010_nominee_image'),
    ]

    operations = [
    ]
