# Generated by Django 2.0.7 on 2018-07-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0012_auto_20180719_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominee',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
    ]
