# Generated by Django 2.0.7 on 2018-07-21 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_summary'),
        ('blog', '0002_auto_20180721_1432'),
    ]

    operations = [
    ]
