# Generated by Django 2.0.7 on 2018-07-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180719_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_more_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='is_most_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
