# Generated by Django 2.0.7 on 2018-07-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(default='Write the executive summary ...')),
                ('get_involved', models.TextField(default='Write the executive summary ...')),
                ('faq', models.TextField(default='Write the executive summary ...')),
                ('contact', models.TextField(default='Write the executive summary ...')),
            ],
        ),
    ]
