# Generated by Django 2.0.7 on 2018-07-22 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about',
            field=models.TextField(default='This porject is for providing the basc of Election results and more. ...'),
        ),
        migrations.AlterField(
            model_name='about',
            name='contact',
            field=models.TextField(default='You can contact us through emails, github or more ...'),
        ),
        migrations.AlterField(
            model_name='about',
            name='faq',
            field=models.TextField(default='Some of the FAQ will be answered here, if you are looking for FQA about getting involved please check the get involved page. ...'),
        ),
        migrations.AlterField(
            model_name='about',
            name='get_involved',
            field=models.TextField(default='This project is opensource and you can contribure and get involved when ever you like ...'),
        ),
    ]
