# Generated by Django 2.0.7 on 2018-07-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Province Name')),
                ('formation_date', models.DateField(verbose_name='Province was formed on')),
                ('capital_city', models.CharField(max_length=50, verbose_name='Capital City')),
                ('area', models.IntegerField()),
                ('population', models.IntegerField()),
                ('voters', models.IntegerField()),
                ('chief_minister', models.CharField(max_length=50, verbose_name='Chief Minister')),
                ('speaker', models.CharField(max_length=50)),
                ('governor', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Province',
                'verbose_name_plural': 'Provinces',
            },
        ),
    ]
