# Generated by Django 2.1.5 on 2019-06-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('political_divisions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
