# Generated by Django 2.0.7 on 2018-07-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('political_divisions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='province',
            options={'verbose_name': 'Province', 'verbose_name_plural': 'Provinces'},
        ),
        migrations.AddField(
            model_name='province',
            name='voters',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
