# Generated by Django 2.1.5 on 2019-06-19 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('political_divisions', '0002_province_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='province',
            name='slug',
        ),
    ]
