# Generated by Django 2.1.5 on 2019-06-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('political_divisions', '0003_remove_province_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
