# Generated by Django 2.1.5 on 2019-06-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('political_divisions', '0005_remove_province_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='pradesh_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
